# Generated by Django 4.2.5 on 2023-10-10 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_category_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name': 'Категорию', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterUniqueTogether(
            name='category',
            unique_together=set(),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['name'], name='app_categor_name_ecc82f_idx'),
        ),
    ]
