# Generated by Django 4.2.5 on 2023-10-10 14:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_category_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default=datetime.datetime(2023, 10, 10, 14, 59, 40, 197152, tzinfo=datetime.timezone.utc), upload_to='post-images'),
            preserve_default=False,
        ),
    ]
